#!/usr/bin/env bash
#
# Fetch and convert a curated set of GeoJSON maps into src/map/.
#
# This script is run *manually* by maintainers when refreshing the map
# bundle; the resulting JSON files are committed to the repo so end users
# get them deterministically without internet access during `npm run build`.
#
# Sources are public-domain or permissively licensed. See src/map/SOURCES.md
# for the per-file attribution that this script writes alongside its output.
#
# Requirements: bash, curl, jq, npx (for mapshaper simplification and
# topojson-client when converting TopoJSON → GeoJSON).
#
# Usage:
#   scripts/fetch-maps.sh             # fetch all
#   scripts/fetch-maps.sh world usa   # fetch a subset by name

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MAP_DIR="$ROOT_DIR/src/map"
SOURCES_FILE="$MAP_DIR/SOURCES.md"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required tool: $1" >&2
    exit 1
  }
}

require curl
require jq

# Target byte cap per file after simplification. Files larger than this
# are passed through mapshaper with a tighter simplify percentage until
# they fit. ECharts only needs visual fidelity at country/state scale,
# so coordinate precision is reduced to 4 decimals (~11m).
TARGET_BYTES=600000

# Keys are the map name (the string passed to echarts.registerMap and
# loadMap). Values are "<source-url>|<format>|<license>".
# Sources favor permissively licensed, English-labeled GeoJSON with
# country/region/state-level granularity (not electoral or local-authority
# detail, which blow past the size budget without adding dashboard value).
declare -A SOURCES=(
  [world]="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson|geojson|Public domain (Natural Earth)"
  [usa]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/united-states.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [germany]="https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/3_mittel.geo.json|geojson|CC0 (deutschlandGeoJSON)"
  [france]="https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/regions.geojson|geojson|Open licence 2.0 (France)"
  [united-kingdom]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/united-kingdom.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [italy]="https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson|geojson|CC-BY 4.0 (Openpolis)"
  [spain]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/spain-communities.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [brazil]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/brazil-states.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [india]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/india.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [japan]="https://raw.githubusercontent.com/dataofjapan/land/master/japan.geojson|geojson|MIT (dataofjapan/land)"
  [china-en]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/china.geojson|geojson|MIT (codeforgermany/click_that_hood)"
)

names=("$@")
if [ "${#names[@]}" -eq 0 ]; then
  names=("${!SOURCES[@]}")
fi

mkdir -p "$MAP_DIR"

write_sources_header() {
  cat >"$SOURCES_FILE" <<'EOF'
# Bundled map sources

This directory is regenerated by `scripts/fetch-maps.sh`. Each map's source
URL and license are listed below for attribution. Maps are fetched at
maintenance time and committed verbatim (minified) so the plugin has no
network dependency at build or runtime. Geometry is simplified by
[mapshaper](https://github.com/mbloch/mapshaper) to keep each file under
~600 KB; coordinate precision is reduced to 4 decimals (~11 m) which is
plenty for echarts at panel scale.

`china.json` predates this script — it was inherited from upstream
`bilibala-echarts-panel` and is preserved unchanged for backwards
compatibility with dashboards that bind data by Chinese-language province
names. `china-en.json` is the English-labeled sibling for international
dashboards (see [docs/maps.md](../../docs/maps.md#picking-the-right-china-map)
for a side-by-side comparison).

## Normalization

Every feature is post-processed by `fetch-maps.sh` to guarantee:

- `properties.name` — the English label (hoisted from source-specific
  keys like `NAME_EN`, `nom`, `reg_name`, `nam`).
- `properties.nameAscii` — a diacritic-stripped variant (`"Île-de-France"`
  → `"Ile-de-France"`) for variable-driven dashboards.

## Per-map notes

- **`usa.json`** — the upstream `click_that_hood/united-states.geojson`
  ships 49 features: 48 contiguous states + the District of Columbia.
  Alaska and Hawaii are absent and would need a custom GeoJSON drop-in.
- **`japan.json`** — administrative suffixes (`Ken`, `Fu`, `To`, `Do`)
  are stripped from prefecture names (`"Kyoto Fu"` → `"Kyoto"`).
- **`china-en.json`** — the upstream label `"Heilongjian"` is corrected
  to `"Heilongjiang"` during the fetch.
- **`world.json`** — Natural Earth 50m countries; coastline detail is
  preserved at the highest simplify percentage that fits the budget.

| File | Source | License | Features | Bytes |
| --- | --- | --- | --- | --- |
| `china.json` | Inherited from upstream `bilibala-echarts-panel` (no recorded provenance) | (upstream) | 34 | 496466 |
EOF
}

if [ ! -f "$SOURCES_FILE" ] || [ "${#names[@]}" -ge "${#SOURCES[@]}" ]; then
  write_sources_header
fi

for name in "${names[@]}"; do
  spec="${SOURCES[$name]:-}"
  if [ -z "$spec" ]; then
    echo "unknown map: $name" >&2
    exit 1
  fi
  IFS='|' read -r url format license <<<"$spec"

  echo "fetching $name ($format) from $url"
  raw="$TMP_DIR/$name.raw.json"
  curl -fsSL "$url" -o "$raw"

  geo="$TMP_DIR/$name.geo.json"
  case "$format" in
    geojson)
      cp "$raw" "$geo"
      ;;
    topojson:*)
      object="${format#topojson:}"
      require npx
      npx --yes topojson-client topo2geo -i "$raw" "$object=$geo" >/dev/null 2>&1
      ;;
    *)
      echo "unknown format: $format" >&2
      exit 1
      ;;
  esac

  # Normalize properties: hoist the most common name keys (NAME, ADMIN,
  # NAME_EN, name_en, name) to a single lowercase "name" so users can
  # bind data without caring about source-specific casing. Add a
  # diacritic-stripped "nameAscii" companion for keys like "Cote d'Ivoire".
  normalized="$TMP_DIR/$name.norm.json"
  jq -c --arg mapName "$name" '
    def stripDiacritics:
      gsub("[àáâãäåāăą]"; "a")
      | gsub("[ÀÁÂÃÄÅĀĂĄ]"; "A")
      | gsub("[èéêëēĕėęě]"; "e")
      | gsub("[ÈÉÊËĒĔĖĘĚ]"; "E")
      | gsub("[ìíîïĩīĭįı]"; "i")
      | gsub("[ÌÍÎÏĨĪĬĮİ]"; "I")
      | gsub("[òóôõöøōŏő]"; "o")
      | gsub("[ÒÓÔÕÖØŌŎŐ]"; "O")
      | gsub("[ùúûüũūŭůű]"; "u")
      | gsub("[ÙÚÛÜŨŪŬŮŰ]"; "U")
      | gsub("[ñńņň]"; "n")
      | gsub("[ÑŃŅŇ]"; "N")
      | gsub("[çćĉċč]"; "c")
      | gsub("[ÇĆĈĊČ]"; "C")
      | gsub("[ßẞ]"; "ss");
    def pickName($p):
      first(
        ($p.NAME_EN, $p.name_en,
         $p.NAME, $p.name,
         $p.ADMIN, $p.admin,
         $p.reg_name, $p.prov_name,
         $p.nam, $p.nom,
         $p.STATE_NAME, $p.state_name)
        | select(type == "string" and . != "" and . != "null")
      ) // "unknown";
    # Per-map fixups for known upstream label quirks. Keep this list short
    # and obvious; deeper renames belong in a separate translation table.
    def fixupName($map; $n):
      if $map == "china-en" and $n == "Heilongjian" then "Heilongjiang"
      elif $map == "japan" then ($n | sub(" (Ken|Fu|To|Do)$"; ""))
      else $n end;
    .features |= map(
      .properties as $p
      | .properties.name = (pickName($p) | fixupName($mapName; .))
      | .properties.nameAscii = (.properties.name | stripDiacritics)
    )
  ' "$geo" >"$normalized"

  # Simplify with mapshaper at progressively tighter percentages until
  # the output fits TARGET_BYTES. Falls back to raw normalized GeoJSON
  # when mapshaper is unavailable.
  out="$MAP_DIR/$name.json"
  simplified=""
  if command -v npx >/dev/null 2>&1; then
    for pct in 25 12 6 3 1.5 0.8; do
      candidate="$TMP_DIR/$name.simp.$pct.json"
      npx --yes mapshaper "$normalized" \
        -simplify "${pct}%" keep-shapes \
        -clean \
        -o precision=0.0001 format=geojson "$candidate" \
        >/dev/null 2>&1 || continue
      size=$(wc -c <"$candidate" | tr -d ' ')
      if [ "$size" -le "$TARGET_BYTES" ]; then
        simplified="$candidate"
        echo "  simplified at ${pct}% → $size bytes"
        break
      fi
      simplified="$candidate"   # keep the smallest attempt so far
    done
  fi
  if [ -z "$simplified" ]; then
    simplified="$normalized"
  fi
  jq -c '.' "$simplified" >"$out"

  size=$(wc -c <"$out" | tr -d ' ')
  count=$(jq '.features | length' "$out")
  echo "  → $out ($size bytes, $count features)"

  echo "| \`$name.json\` | $url | $license | $count | $size |" >>"$SOURCES_FILE"
done

echo
echo "done. Commit src/map/*.json and SOURCES.md."
