#!/usr/bin/env bash
#
# Fetch and convert a curated set of GeoJSON maps into src/map/.
#
# This script is run *manually* by maintainers when refreshing the map
# bundle; the resulting JSON files are committed to the repo so end users
# get them deterministically without internet access during `npm run build`.
#
# Sources are public-domain or permissively licensed. See src/map/SOURCES.md
# for the per-file attribution that this script writes alongside its output.
#
# Requirements: bash, curl, jq, npx (for topojson-client when converting
# TopoJSON → GeoJSON).
#
# Usage:
#   scripts/fetch-maps.sh             # fetch all
#   scripts/fetch-maps.sh world usa   # fetch a subset by name

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MAP_DIR="$ROOT_DIR/src/map"
SOURCES_FILE="$MAP_DIR/SOURCES.md"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required tool: $1" >&2
    exit 1
  }
}

require curl
require jq

# Keys are the map name (the string passed to echarts.registerMap and
# loadMap). Values are "<source-url>|<format>|<license>".
declare -A SOURCES=(
  [world]="https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson|geojson|Public domain (Natural Earth)"
  [usa]="https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json|topojson:states|ISC (world-atlas, Mike Bostock)"
  [germany]="https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/3_mittel.geo.json|geojson|CC0 (deutschlandGeoJSON)"
  [france]="https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/regions.geojson|geojson|Open licence 2.0 (France)"
  [united-kingdom]="https://raw.githubusercontent.com/martinjc/UK-GeoJSON/master/json/electoral/gb/wpc.json|geojson|OGL v3 (UK Government)"
  [italy]="https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson|geojson|CC-BY 4.0 (Openpolis)"
  [spain]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/spain-communities.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [brazil]="https://raw.githubusercontent.com/codeforgermany/click_that_hood/master/public/data/brazil-states.geojson|geojson|MIT (codeforgermany/click_that_hood)"
  [india]="https://raw.githubusercontent.com/geohacker/india/master/state/india_telengana.geojson|geojson|MIT (geohacker/india)"
  [japan]="https://raw.githubusercontent.com/dataofjapan/land/master/japan.geojson|geojson|MIT (dataofjapan/land)"
)

names=("$@")
if [ "${#names[@]}" -eq 0 ]; then
  names=("${!SOURCES[@]}")
fi

mkdir -p "$MAP_DIR"

write_sources_header() {
  cat >"$SOURCES_FILE" <<'EOF'
# Bundled map sources

This directory is regenerated by `scripts/fetch-maps.sh`. Each map's source
URL and license are listed below for attribution. Maps are fetched at
maintenance time and committed verbatim (minified) so the plugin has no
network dependency at build or runtime.

| File | Source | License |
| --- | --- | --- |
EOF
}

if [ ! -f "$SOURCES_FILE" ] || [ "${#names[@]}" -ge "${#SOURCES[@]}" ]; then
  write_sources_header
fi

for name in "${names[@]}"; do
  spec="${SOURCES[$name]:-}"
  if [ -z "$spec" ]; then
    echo "unknown map: $name" >&2
    exit 1
  fi
  IFS='|' read -r url format license <<<"$spec"

  echo "fetching $name ($format) from $url"
  raw="$TMP_DIR/$name.raw.json"
  curl -fsSL "$url" -o "$raw"

  out="$MAP_DIR/$name.json"
  case "$format" in
    geojson)
      jq -c '.' "$raw" >"$out"
      ;;
    topojson:*)
      object="${format#topojson:}"
      require npx
      npx --yes -p topojson-client topojson-client@latest -o "$TMP_DIR/$name.geo.json" -O "$object" -- "$raw" >/dev/null 2>&1 || \
        npx --yes topojson-client topo2geo -i "$raw" "$object=$TMP_DIR/$name.geo.json"
      jq -c '.' "$TMP_DIR/$name.geo.json" >"$out"
      ;;
    *)
      echo "unknown format: $format" >&2
      exit 1
      ;;
  esac

  size=$(wc -c <"$out" | tr -d ' ')
  echo "  → $out ($size bytes)"

  echo "| \`$name.json\` | $url | $license |" >>"$SOURCES_FILE"
done

echo
echo "done. Commit src/map/*.json and SOURCES.md."
